version: "3.8"
services:
    mongoDB:
        image: mongo:latest
        expose:
            - 27017
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ./mongodb/storage/:/data/db
